#!/usr/bin/env node
import { spawnSync } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const brands = ["client1", "client2"];
const brandFile = path.join(
  projectRoot,
  "src",
  "brands",
  "brand.generated.ts"
);

function run(command, args, env = {}) {
  const result = spawnSync(command, args, {
    cwd: projectRoot,
    env: { ...process.env, ...env },
    stdio: "inherit",
    shell: true,
  });
  if (result.status !== 0) {
    process.exit(result.status || 1);
  }
}

function writeBrand(brand) {
  const contents = `/**
 * Generated by scripts/build-brands.js — do not edit by hand.
 */
export const BUILD_ACUL_BRAND: "client1" | "client2" = "${brand}";
`;
  fs.writeFileSync(brandFile, contents, "utf8");
  console.log(`Wrote ${path.relative(projectRoot, brandFile)} = ${brand}`);
}

for (const brand of brands) {
  console.log(`\nBuilding brand: ${brand}`);
  writeBrand(brand);

  const outDir = path.join(projectRoot, "dist-brands", brand);
  fs.rmSync(outDir, { recursive: true, force: true });

  run(process.platform === "win32" ? "npx.cmd" : "npx", ["tsc"], {
    VITE_ACUL_BRAND: brand,
  });
  run(
    process.platform === "win32" ? "npx.cmd" : "npx",
    ["vite", "build", "--logLevel", "info"],
    { VITE_ACUL_BRAND: brand }
  );

  const commonJs = path.join(outDir, "shared", "common.js");
  if (!fs.existsSync(commonJs)) {
    console.error(`Missing ${commonJs}`);
    process.exit(1);
  }
  const js = fs.readFileSync(commonJs, "utf8");
  const hasTeal = js.includes("0F766E");
  const hasRed = js.includes("DC2626");
  const hasGrey = js.includes("6D6E71");
  const hasClient2Badge = js.includes("Client 2");
  console.log(
    `Verify ${brand}: teal=${hasTeal} red=${hasRed} grey=${hasGrey} client2Badge=${hasClient2Badge}`
  );

  if (brand === "client1" && (hasTeal || hasRed || hasClient2Badge)) {
    console.error(
      "ERROR: client1 bundle still contains client2 theme markers."
    );
    process.exit(1);
  }
  if (brand === "client2" && !hasRed) {
    console.error("ERROR: client2 bundle missing red theme markers.");
    process.exit(1);
  }
}

// Restore default for local `npm run dev`
writeBrand("client1");

console.log(
  "\nBrand builds ready under dist-brands/client1 and dist-brands/client2"
);
console.log("CRITICAL: upload to matching folders only (CDN client1 was mixed before):");
console.log(
  "  dist-brands/client1/* -> https://acul.innodeed.com/assets/client1/"
);
console.log(
  "  dist-brands/client2/* -> https://acul.innodeed.com/assets/client2/"
);
console.log(
  "  cdn/acul-loader.js    -> https://acul.innodeed.com/assets/acul-loader.js"
);
