#!/usr/bin/env node
import { spawnSync } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const brand = (process.argv[2] || "").trim().toLowerCase();
if (brand !== "client1" && brand !== "client2") {
  console.error("Usage: node ./scripts/dev-brand.js <client1|client2>");
  process.exit(1);
}

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const brandFile = path.join(projectRoot, "src", "brands", "brand.generated.ts");
fs.writeFileSync(
  brandFile,
  `/**
 * Generated by scripts/dev-brand.js — do not edit by hand.
 */
export const BUILD_ACUL_BRAND: "client1" | "client2" = "${brand}";
`,
  "utf8"
);
console.log(`Starting Vite with BUILD_ACUL_BRAND=${brand}`);

const result = spawnSync(
  process.platform === "win32" ? "npx.cmd" : "npx",
  ["vite", "dev"],
  {
    cwd: projectRoot,
    env: { ...process.env, VITE_ACUL_BRAND: brand },
    stdio: "inherit",
    shell: true,
  }
);

process.exit(result.status || 0);
